CREATE USER UDONG IDENTIFIED BY UDONG;
GRANT CONNECT, RESOURCE TO UDONG;

DROP TABLE FAQ;
DROP TABLE INQUIRY;
DROP TABLE NOTICE;
DROP TABLE CHATMESSAGE;
DROP TABLE CHATROOM;
DROP TABLE REMOVE_REQUEST;
DROP TABLE REVIEW;
DROP TABLE RESERVATION;
DROP TABLE ZZIM;
DROP TABLE HOUSE_IMG;
DROP TABLE MANAGE_INFO;
DROP TABLE MANAGE;
DROP TABLE OPTION_INFO;
DROP TABLE OPTIONS;
DROP TABLE HOUSE;
DROP TABLE SUBWAY;
DROP TABLE AGENT;
DROP TABLE MEMBER;

DROP SEQUENCE SEQ_FAQ;
DROP SEQUENCE SEQ_INQ;
DROP SEQUENCE SEQ_NOT;
DROP SEQUENCE SEQ_MES;
DROP SEQUENCE SEQ_CHA;
DROP SEQUENCE SEQ_REM;
DROP SEQUENCE SEQ_REV;
DROP SEQUENCE SEQ_RES;
DROP SEQUENCE SEQ_SUB;
DROP SEQUENCE SEQ_MAN;
DROP SEQUENCE SEQ_OPT;
DROP SEQUENCE SEQ_HOU;
DROP SEQUENCE SEQ_AGE;
DROP SEQUENCE SEQ_MEM;

-- 개인회원 --

CREATE TABLE MEMBER (
	MEMBER_NO NUMBER PRIMARY KEY,
	MEMBER_ID VARCHAR2(18) NOT NULL UNIQUE,
	MEMBER_PWD VARCHAR2(100) NOT NULL,
	MEMBER_NAME VARCHAR2(18) NOT NULL,
	MEMBER_PHONE VARCHAR2(11) NOT NULL,
	MEMBER_EMAIL VARCHAR2(40) NOT NULL,
	STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN ('Y', 'N'))
);

COMMENT ON COLUMN MEMBER.MEMBER_NO IS '개인회원번호';
COMMENT ON COLUMN MEMBER.MEMBER_ID IS '개인회원아이디';
COMMENT ON COLUMN MEMBER.MEMBER_PWD IS '개인회원비밀번호';
COMMENT ON COLUMN MEMBER.MEMBER_NAME IS '개인회원이름';
COMMENT ON COLUMN MEMBER.MEMBER_PHONE IS '개인회원연락처';
COMMENT ON COLUMN MEMBER.MEMBER_EMAIL IS '개인회원이메일';
COMMENT ON COLUMN MEMBER.STATUS IS '활성화 여부';

CREATE SEQUENCE SEQ_MEM
NOCACHE;

-- 업체회원 --

CREATE TABLE AGENT (
	AGENT_NO NUMBER PRIMARY KEY,
	AGENT_ID VARCHAR2(18) NOT NULL UNIQUE,
	AGENT_PWD VARCHAR2(100) NOT NULL,
	AGENT_NAME VARCHAR2(50) NOT NULL,
	AGENT_PHONE VARCHAR2(11) NOT NULL,
	AGENT_EMAIL VARCHAR2(40) NOT NULL,
	AGENT_ADDRESS VARCHAR2(150) NOT NULL,
	INTRODUCE VARCHAR2(600) NOT NULL,
	STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN ('Y', 'N')),
	PERMISSION VARCHAR2(1) DEFAULT 'N' CHECK (PERMISSION IN ('Y', 'N')),
	COMPANY_NO VARCHAR2(10) NOT NULL,
	CEO_NAME VARCHAR2(20) NOT NULL,
	DOCUMENT1 VARCHAR2(300) NOT NULL,
	DOCUMENT2 VARCHAR2(300) NOT NULL
);

COMMENT ON COLUMN AGENT.AGENT_NO IS '업체회원번호';
COMMENT ON COLUMN AGENT.AGENT_ID IS '업체회원아이디';
COMMENT ON COLUMN AGENT.AGENT_PWD IS '업체회원비밀번호';
COMMENT ON COLUMN AGENT.AGENT_NAME IS '업체명';
COMMENT ON COLUMN AGENT.AGENT_PHONE IS '업체연락처';
COMMENT ON COLUMN AGENT.AGENT_EMAIL IS '업체이메일';
COMMENT ON COLUMN AGENT.AGENT_ADDRESS IS '업체주소';
COMMENT ON COLUMN AGENT.INTRODUCE IS '업체소개글';
COMMENT ON COLUMN AGENT.STATUS IS '활성화 여부';
COMMENT ON COLUMN AGENT.PERMISSION IS '가입 승인 여부';
COMMENT ON COLUMN AGENT.COMPANY_NO IS '사업자등록번호';
COMMENT ON COLUMN AGENT.CEO_NAME IS '대표자명';
COMMENT ON COLUMN AGENT.DOCUMENT1 IS '사업자등록증 파일 경로';
COMMENT ON COLUMN AGENT.DOCUMENT2 IS '중개사등록증 파일 경로';

CREATE SEQUENCE SEQ_AGE
NOCACHE;

-- 지하철 --

CREATE TABLE SUBWAY (
	SUBWAY_NO NUMBER PRIMARY KEY,
	STATION VARCHAR2(100) NOT NULL,
	LINE VARCHAR2(30) NOT NULL
);

COMMENT ON COLUMN SUBWAY.SUBWAY_NO IS '지하철역 번호';
COMMENT ON COLUMN SUBWAY.STATION IS '지하철역 이름';
COMMENT ON COLUMN SUBWAY.LINE IS '호선 정보';

CREATE SEQUENCE SEQ_SUB
NOCACHE;

-- 매물 --

CREATE TABLE HOUSE (
	HOUSE_NO NUMBER PRIMARY KEY,
	AGENT_NO NUMBER NOT NULL,
	TITLE VARCHAR2(300) NOT NULL,
	DESCRIPTION VARCHAR2(3000) NOT NULL,
	THUMBNAIL VARCHAR2(300),
	SALES_TYPE VARCHAR2(20) NOT NULL,
	ADDRESS1 VARCHAR2(100) NOT NULL,
	ADDRESS2 VARCHAR2(100) NOT NULL,
	ZIP_CODE VARCHAR2(5) NOT NULL,
	BUILDING_TYPE VARCHAR2(100) NOT NULL,
	BUILDING_FLOOR VARCHAR2(20) NOT NULL,
	SUBWAY_NO NUMBER NOT NULL,
	DEPOSIT NUMBER NOT NULL,
	MONTHLY_COST NUMBER DEFAULT 0 NOT NULL,
	MANAGE_COST NUMBER NOT NULL,
	FLOOR VARCHAR2(20) NOT NULL,
	ROOM_TYPE VARCHAR2(100) NOT NULL,
	DIRECTION VARCHAR2(15) NOT NULL,
	PARKING NUMBER DEFAULT 0 NOT NULL,
	LAT VARCHAR2(30) NOT NULL,
	LNG VARCHAR2(30) NOT NULL,
	SIZE_M2 NUMBER NOT NULL,
	SIZE_P NUMBER NOT NULL,
	PET VARCHAR2(6) DEFAULT '불가' CHECK (PET IN ('가능', '불가')) NOT NULL ,
	LOAN VARCHAR2(6) DEFAULT '불가' CHECK (LOAN IN ('가능', '불가')) NOT NULL ,
    STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN ('Y', 'N')),
	MOVEIN_DATE VARCHAR2(30) NOT NULL,
	REG_DATE DATE DEFAULT SYSDATE NOT NULL ,
	VIEW_COUNT NUMBER DEFAULT 0 NOT NULL ,
	REPORT_COUNT NUMBER DEFAULT 0 NOT NULL ,
	SALES_STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (SALES_STATUS IN ('Y', 'N')) NOT NULL,
    FOREIGN KEY(AGENT_NO) REFERENCES AGENT (AGENT_NO),
    FOREIGN KEY(SUBWAY_NO) REFERENCES SUBWAY (SUBWAY_NO)
);

COMMENT ON COLUMN HOUSE.HOUSE_NO IS '매물 번호';
COMMENT ON COLUMN HOUSE.AGENT_NO IS '매물을 등록한 중개사무소 번호 ';
COMMENT ON COLUMN HOUSE.TITLE IS '매물 제목';
COMMENT ON COLUMN HOUSE.DESCRIPTION IS '매물 상세설명';
COMMENT ON COLUMN HOUSE.THUMBNAIL IS '매물 대표사진 파일경로';
COMMENT ON COLUMN HOUSE.SALES_TYPE IS '계약유형(월세/전세)';
COMMENT ON COLUMN HOUSE.ADDRESS1 IS '시/군/구/도로명';
COMMENT ON COLUMN HOUSE.ADDRESS2 IS '상세주소';
COMMENT ON COLUMN HOUSE.ZIP_CODE IS '우편번호';
COMMENT ON COLUMN HOUSE.BUILDING_TYPE IS '건물 유형 (다가구/오피스텔 등)';
COMMENT ON COLUMN HOUSE.BUILDING_FLOOR IS '건물 전체 층수';
COMMENT ON COLUMN HOUSE.SUBWAY_NO IS '가장 가까운 지하철역 정보';
COMMENT ON COLUMN HOUSE.DEPOSIT IS '월세 : 보증금 / 전세 : 전세금';
COMMENT ON COLUMN HOUSE.MONTHLY_COST IS '월세';
COMMENT ON COLUMN HOUSE.MANAGE_COST IS '관리비';
COMMENT ON COLUMN HOUSE.FLOOR IS '매물이 위치한 층수';
COMMENT ON COLUMN HOUSE.ROOM_TYPE IS '방 유형(오픈형/분리형/복층 등)';
COMMENT ON COLUMN HOUSE.DIRECTION IS '방향(남향/동향/북향 등)';
COMMENT ON COLUMN HOUSE.PARKING IS '주차 가능 대수';
COMMENT ON COLUMN HOUSE.LAT IS '위도';
COMMENT ON COLUMN HOUSE.LNG IS '경도';
COMMENT ON COLUMN HOUSE.SIZE_M2 IS '전용면적(제곱미터)';
COMMENT ON COLUMN HOUSE.SIZE_P IS '전용면적(평)';
COMMENT ON COLUMN HOUSE.PET IS '반려동물 동반 가능 여부';
COMMENT ON COLUMN HOUSE.LOAN IS '전세대출 가능 여부';
COMMENT ON COLUMN HOUSE.MOVEIN_DATE IS '입주가능일';
COMMENT ON COLUMN HOUSE.STATUS IS '활성화 여부';
COMMENT ON COLUMN HOUSE.VIEW_COUNT IS '조회수';
COMMENT ON COLUMN HOUSE.REPORT_COUNT IS '신고 당한 수';
COMMENT ON COLUMN HOUSE.SALES_STATUS IS '계약 가능 여부';

CREATE SEQUENCE SEQ_HOU
NOCACHE;

-- 옵션 항목 --

CREATE TABLE OPTIONS (
   OPTION_NO NUMBER PRIMARY KEY,
   OPTION_NAME VARCHAR2(100) NOT NULL
);

COMMENT ON COLUMN OPTIONS.OPTION_NO IS '옵션 번호';
COMMENT ON COLUMN OPTIONS.OPTION_NAME IS '옵션명';

CREATE SEQUENCE SEQ_OPT
NOCACHE;

-- 매물 옵션 정보 --

CREATE TABLE OPTION_INFO (
   HOUSE_NO NUMBER NOT NULL,
   OPTION_NO NUMBER NOT NULL,
   FOREIGN KEY(HOUSE_NO) REFERENCES HOUSE (HOUSE_NO),
   FOREIGN KEY(OPTION_NO) REFERENCES OPTIONS (OPTION_NO)
);

COMMENT ON COLUMN OPTION_INFO.HOUSE_NO IS '매물 번호';
COMMENT ON COLUMN OPTION_INFO.OPTION_NO IS '옵션 번호';

-- 관리비 항목--

CREATE TABLE MANAGE (
   MANAGE_NO NUMBER PRIMARY KEY,
   MANAGE_NAME VARCHAR2(30) NOT NULL
);

COMMENT ON COLUMN MANAGE.MANAGE_NO IS '관리비항목 번호';
COMMENT ON COLUMN MANAGE.MANAGE_NAME IS '항목명';

CREATE SEQUENCE SEQ_MAN
NOCACHE;

-- 매물 관리비 정보 --

CREATE TABLE MANAGE_INFO (
   HOUSE_NO NUMBER NOT NULL,
   MANAGE_NO NUMBER NOT NULL,
   FOREIGN KEY(HOUSE_NO) REFERENCES HOUSE (HOUSE_NO),
   FOREIGN KEY(MANAGE_NO) REFERENCES MANAGE (MANAGE_NO)
);

COMMENT ON COLUMN MANAGE_INFO.HOUSE_NO IS '매물 번호';
COMMENT ON COLUMN MANAGE_INFO.MANAGE_NO IS '관리비항목 번호';

-- 매물 사진 파일 경로 --

CREATE TABLE HOUSE_IMG (
   HOUSE_NO NUMBER NOT NULL,
   IMG_PATH VARCHAR2(300) NOT NULL,
   FOREIGN KEY(HOUSE_NO) REFERENCES HOUSE (HOUSE_NO)
);

COMMENT ON COLUMN HOUSE_IMG.HOUSE_NO IS '매물 번호';
COMMENT ON COLUMN HOUSE_IMG.IMG_PATH IS '사진 경로';

-- 찜한 매물 목록 --

CREATE TABLE ZZIM (
   MEMBER_NO NUMBER NOT NULL,
   HOUSE_NO NUMBER NOT NULL,
   FOREIGN KEY(MEMBER_NO) REFERENCES MEMBER (MEMBER_NO),
   FOREIGN KEY(HOUSE_NO) REFERENCES HOUSE (HOUSE_NO)
);

COMMENT ON COLUMN ZZIM.MEMBER_NO IS '일반회원 번호';
COMMENT ON COLUMN ZZIM.HOUSE_NO IS '매물 번호';

-- 방문 예약 --

CREATE TABLE RESERVATION (
	RESERVATION_NO NUMBER PRIMARY KEY,
	MEMBER_NO NUMBER NOT NULL,
	AGENT_NO NUMBER NOT NULL,
	HOUSE_NO NUMBER NOT NULL,
	RESERVATION_DATE DATE NOT NULL,
	RESERVATION_TIME VARCHAR2(10) NOT NULL,
	CONTENT VARCHAR2(600),
	RESULT VARCHAR2(30) NOT NULL,
	DEPOSIT VARCHAR2(30) NOT NULL,
	CREATE_DATE DATE DEFAULT SYSDATE NOT NULL,
	CID VARCHAR2(30),
	TID VARCHAR2(30),
	CANCEL_AMOUNT NUMBER,
	CANCEL_TAX_FREE_AMOUNT NUMBER,
    FOREIGN KEY(MEMBER_NO) REFERENCES MEMBER (MEMBER_NO),
    FOREIGN KEY(AGENT_NO) REFERENCES AGENT (AGENT_NO),
    FOREIGN KEY(HOUSE_NO) REFERENCES HOUSE (HOUSE_NO)
);

COMMENT ON COLUMN RESERVATION.RESERVATION_NO IS '예약 번호';
COMMENT ON COLUMN RESERVATION.MEMBER_NO IS '예약자';
COMMENT ON COLUMN RESERVATION.AGENT_NO IS '문의 업체';
COMMENT ON COLUMN RESERVATION.HOUSE_NO IS '문의 매물';
COMMENT ON COLUMN RESERVATION.RESERVATION_DATE IS '예약일(방문 예정일)';
COMMENT ON COLUMN RESERVATION.RESERVATION_TIME IS '예약 시간(방문 예정시간)';
COMMENT ON COLUMN RESERVATION.CONTENT IS '사전 문의 내용';
COMMENT ON COLUMN RESERVATION.RESULT IS '예약 상태 (방문대기/예약 취소/미방문/방문 완료)';
COMMENT ON COLUMN RESERVATION.DEPOSIT IS '예약금 결제 상태 (결제 완료/환불 완료/환불 불가)';
COMMENT ON COLUMN RESERVATION.CREATE_DATE IS '예약 생성일';

CREATE SEQUENCE SEQ_RES
NOCACHE;

-- 리뷰 --

CREATE TABLE REVIEW (
	REVIEW_NO NUMBER PRIMARY KEY,
	MEMBER_NO NUMBER NOT NULL,
	AGENT_NO NUMBER NOT NULL,
	RESERVATION_NO NUMBER,
	CONTENT VARCHAR2(600) NOT NULL,
	SATISFIED VARCHAR2(10) NOT NULL,
	CREATE_DATE DATE DEFAULT SYSDATE NOT NULL,
	STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN ('Y', 'N')) NOT NULL,
    FOREIGN KEY(MEMBER_NO) REFERENCES MEMBER (MEMBER_NO),
    FOREIGN KEY(AGENT_NO) REFERENCES AGENT (AGENT_NO),
    FOREIGN KEY(RESERVATION_NO) REFERENCES RESERVATION (RESERVATION_NO)
);

COMMENT ON COLUMN REVIEW.REVIEW_NO IS '리뷰 번호';
COMMENT ON COLUMN REVIEW.MEMBER_NO IS '작성자';
COMMENT ON COLUMN REVIEW.AGENT_NO IS '대상 업체';
COMMENT ON COLUMN REVIEW.RESERVATION_NO IS '예약 정보';
COMMENT ON COLUMN REVIEW.CONTENT IS '리뷰 내용';
COMMENT ON COLUMN REVIEW.SATISFIED IS '만족도 (만족/불만족)';
COMMENT ON COLUMN REVIEW.CREATE_DATE IS '리뷰 작성일';
COMMENT ON COLUMN REVIEW.STATUS IS '활성화 여부';

CREATE SEQUENCE SEQ_REV
NOCACHE;

-- 리뷰 삭제 요청 --

CREATE TABLE REMOVE_REQUEST (
	REQUEST_NO NUMBER PRIMARY KEY,
	AGENT_NO NUMBER NOT NULL,
	REVIEW_NO NUMBER NOT NULL,
	REASON VARCHAR2(1000) NOT NULL,
	REQUEST_DATE DATE DEFAULT SYSDATE NOT NULL,
	RESULT VARCHAR2(1) DEFAULT 'D' CHECK (RESULT IN ('Y', 'N', 'D')),
    FOREIGN KEY(AGENT_NO) REFERENCES AGENT (AGENT_NO),
    FOREIGN KEY(REVIEW_NO) REFERENCES REVIEW (REVIEW_NO)
);

COMMENT ON COLUMN REMOVE_REQUEST.REQUEST_NO IS '요청 번호';
COMMENT ON COLUMN REMOVE_REQUEST.AGENT_NO IS '요청 업체';
COMMENT ON COLUMN REMOVE_REQUEST.REVIEW_NO IS '삭제 요청 리뷰';
COMMENT ON COLUMN REMOVE_REQUEST.REASON IS '요청 사유';
COMMENT ON COLUMN REMOVE_REQUEST.REQUEST_DATE IS '요청일';
COMMENT ON COLUMN REMOVE_REQUEST.RESULT IS '처리 결과 (삭제조치/요청반려/대기)';

CREATE SEQUENCE SEQ_REM
NOCACHE;

--채팅방--

CREATE TABLE CHATROOM (
   CHATROOM_NO NUMBER PRIMARY KEY,
   AGENT_NO NUMBER NOT NULL,
   MEMBER_NO NUMBER NOT NULL,
   FOREIGN KEY(AGENT_NO) REFERENCES AGENT (AGENT_NO),
   FOREIGN KEY(MEMBER_NO) REFERENCES MEMBER (MEMBER_NO)
);

COMMENT ON COLUMN CHATROOM.CHATROOM_NO IS '채팅방번호';
COMMENT ON COLUMN CHATROOM.AGENT_NO IS '업체회원번호';
COMMENT ON COLUMN CHATROOM.MEMBER_NO IS '일반회원번호';

CREATE SEQUENCE SEQ_CHA
NOCACHE;

--채팅 메시지--

CREATE TABLE CHATMESSAGE (
   MESSAGE_NO NUMBER PRIMARY KEY,
   CHATROOM_NO NUMBER NOT NULL,
   SENDER_ID VARCHAR2(18) NOT NULL,
   CONTENT VARCHAR2(1000) NOT NULL,
   CHAT_TIME DATE DEFAULT SYSDATE NOT NULL,
   UNREAD VARCHAR2(1) CHECK (UNREAD  IN ('Y', 'N')) NOT NULL,
   FOREIGN KEY(CHATROOM_NO) REFERENCES CHATROOM (CHATROOM_NO)
);

COMMENT ON COLUMN CHATMESSAGE.MESSAGE_NO IS '메시지번호';
COMMENT ON COLUMN CHATMESSAGE.CHATROOM_NO IS '채팅방번호';
COMMENT ON COLUMN CHATMESSAGE.SENDER_ID IS '송신자';
COMMENT ON COLUMN CHATMESSAGE.CONTENT IS '메시지내용';
COMMENT ON COLUMN CHATMESSAGE.CHAT_TIME IS '보낸시간';
COMMENT ON COLUMN CHATMESSAGE.UNREAD IS '수신자확인여부';

CREATE SEQUENCE SEQ_MES
NOCACHE;

-- 공지사항 --

CREATE TABLE NOTICE (
    NOTICE_NO NUMBER PRIMARY KEY,
    TITLE VARCHAR2(500) NOT NULL,
    CONTENT VARCHAR2(2000) NOT NULL,
    CREATE_DATE DATE DEFAULT SYSDATE NOT NULL,
    STATUS  VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN ('Y', 'N'))
);

COMMENT ON COLUMN NOTICE.NOTICE_NO IS '공지사항 번호';
COMMENT ON COLUMN NOTICE.TITLE IS '공지 제목';
COMMENT ON COLUMN NOTICE.CONTENT IS '공지 내용';
COMMENT ON COLUMN NOTICE.CREATE_DATE IS '작성일';
COMMENT ON COLUMN NOTICE.STATUS IS '활성화 여부';

CREATE SEQUENCE SEQ_NOT
NOCACHE;

-- 1:1 문의 --

CREATE TABLE INQUIRY (
    INQUIRY_NO NUMBER PRIMARY KEY,
    MEMBER_NO NUMBER,
    AGENT_NO NUMBER,
    CATEGORY VARCHAR2(30) NOT NULL,
    TITLE VARCHAR2(60) NOT NULL,
    CONTENT VARCHAR2(2000) NOT NULL,
    CREATE_DATE DATE DEFAULT SYSDATE NOT NULL,
    ANSWER_CONTENT VARCHAR2(1000),
    ANSWER_DATE DATE,
    STATUS  VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN ('Y', 'N')),
    FOREIGN KEY(MEMBER_NO) REFERENCES MEMBER (MEMBER_NO),
    FOREIGN KEY(AGENT_NO) REFERENCES AGENT (AGENT_NO)
);

COMMENT ON COLUMN INQUIRY.INQUIRY_NO IS '문의 번호';
COMMENT ON COLUMN INQUIRY.MEMBER_NO IS '일반회원 번호';
COMMENT ON COLUMN INQUIRY.AGENT_NO IS '업체회원 번호';
COMMENT ON COLUMN INQUIRY.CATEGORY IS '문의 분류';
COMMENT ON COLUMN INQUIRY.TITLE IS '문의 제목';
COMMENT ON COLUMN INQUIRY.CONTENT IS '문의 내용';
COMMENT ON COLUMN INQUIRY.CREATE_DATE IS '작성일';
COMMENT ON COLUMN INQUIRY.ANSWER_CONTENT IS '답변 내용';
COMMENT ON COLUMN INQUIRY.ANSWER_DATE IS '답변일';
COMMENT ON COLUMN INQUIRY.STATUS IS '활성화 여부';

CREATE SEQUENCE SEQ_INQ
NOCACHE;

-- 자주 묻는 질문 --

CREATE TABLE FAQ (
    FAQ_NO NUMBER PRIMARY KEY,
    TITLE VARCHAR2(150) NOT NULL,
    CONTENT VARCHAR2(1000) NOT NULL
);

COMMENT ON COLUMN FAQ.FAQ_NO IS 'FAQ 번호';
COMMENT ON COLUMN FAQ.TITLE IS 'FAQ 제목';
COMMENT ON COLUMN FAQ.CONTENT IS 'FAQ 내용';

CREATE SEQUENCE SEQ_FAQ
NOCACHE;



-- 변경사항 1차

* 오타 수정 및 누락 구문 추가

* SUBWAY 테이블
  - SUBWAY_NAME 컬럼명 STATION으로 변경

* HOUSE 테이블
  - THUMBNAIL 컬럼 NOT NULL 제약조건 삭제 (INSERT 과정에서 순서 문제로 인해 삭제)
  - ROOM_COUNT 컬럼 삭제 (ROOM_TYPE 컬럼에 도메인이 '오픈형 원룸 / 분리형 원룸 / 복층형 원룸 / 투룸'으로 구분 예정)
  - MOVEIN_DATE 컬럼 자료형 DATE => VARCHAR2(30)으로 변경 ('입주가능한 날짜' 또는 '즉시입주' 문자열이 들어갈 예정)
  - PET, LOAN 컬럼 DEFAULT '불가', CHECK 제약조건 (컬럼명 IN '가능', '불가')로 변경 (값 출력 시 편의를 위해 변경)

-- 변경사항 2차

* 자료형 변경

AGENT 테이블
- COMPANY_NO 컬럼 NUMBER => VARCHAR2(10)

HOUSE 테이블
- ZIP_CODE 컬럼 NUMBER => VARCHAR2(5)
- LAT / LNG 컬럼 NUMBER => VARCHAR2(30)

NOTICE 테이블
- TITLE 컬럼 VARCHAR2(60) => VARCHAR2(500)

* 제약조건 삭제

CHATMESSAGE 테이블
- UNREAD 컬럼 DEFAULT 'N' 삭제
